### ISSUE TITLE
Setup Config

### ISSUE THREAD

**Issue by HachemBouhadede** [HachemBouhadede/team-nine-pebble-work#1]
**Task title**
Setup Config

**Task description**
Config the necessary dependencies and updates 

**Subtasks**

- [x] upgrade react, NextJS, ESlint to latest 

- [x] add Tailwind

- [x] add team members and trainers

- [x] get the repo ready to be cloned by everyone

- [x] set the default branch, protect it along with develope

**Comment by HachemBouhadede** [comment]
Completed, in your email, you should have recieved links to the repository after being set
I will also manually send the link on Discord
